name: Save User Actions

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  save_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Actions
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          mkdir -p actions_folder
          cp -r $GITHUB_WORKSPACE/. actions_folder
          git add actions_folder
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git commit -m "Saving actions"
          git push
