name: Save User Actions

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  save_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install moreutils
        run: sudo apt-get install -y moreutils
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add user action to JSON
        run: |
          action=$(echo "$GITHUB_EVENT_PATH" | xargs cat)
          json=$(jq --arg action "$action" '.actions |= . + [$action]' actions.json)
          echo "$json" | sponge actions.json
        shell: bash
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
      - name: Save Actions
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add -A
          git commit -m "Saving actions"
          git push -u origin main
    
