name: Save User Actions

on:
  push:
    branches:
      - main

jobs:
  save_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Actions
        run: |
          temp_dir=$(mktemp -d)
          mv $GITHUB_WORKSPACE/* $temp_dir/
          cp -r $temp_dir/. actions_folder
          git add actions_folder
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Saving actions"
          git push
